info:
  profile: default

spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/healthcheck
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
server:
  servlet:
    context-path: /healthcheck_demo
  port: 8280
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'